import InfinityCategories.HigherCategoryTheory.SingleSortedCategory.Basic
import InfinityCategories.HigherCategoryTheory.Nat
import InfinityCategories.HigherCategoryTheory.Unit
import InfinityCategories.Data.NatIndex
