name = "HigherCategoryTheory"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HigherCategoryTheory"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "v4.23.0"

[[require]]
name = "checkdecls"
scope = "PatrickMassot"
rev = "3d425859e73fcfbef85b9638c2a91708ef4a22d4"

[[lean_lib]]
name = "HigherCategoryTheory"
