name = "HigherCategoryTheory"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HigherCategoryTheory"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[lean_lib]]
name = "HigherCategoryTheory"
