# Site information
title: A Formalization of Higher-Order Categories in Lean 4
description: >-
  A formal verification project based on the work by
  Enric Cosme Llópez on "Higher-order categories".
url: "https://mariovagomarzal.github.io/higher_category_theory"
baseurl: ""
repository: mariovagomarzal/higher_category_theory

# Site settings
plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
defaults:
  -
    scope:
      path: ""
    values:
      use_mathjax: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
